SELECT 
    ID,
    START_DATE,
    FINISH_DATE,
    PERIOD_DIFF(DATE_FORMAT(FINISH_DATE, '%Y%m'),
            DATE_FORMAT(START_DATE, '%Y%m')) AS DURATION_MONTHS
FROM
    project
GROUP BY ID , START_DATE , FINISH_DATE , DURATION_MONTHS
HAVING DURATION_MONTHS = (SELECT 
        MAX(PERIOD_DIFF(DATE_FORMAT(FINISH_DATE, '%Y%m'),
                    DATE_FORMAT(START_DATE, '%Y%m')))
    FROM
        project)
